// Mocks generated by Mockito 5.4.6 from annotations
// in movies/test/presentation/pages/movies_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:flutter_bloc/flutter_bloc.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movies/domain/usecases/get_movies_detail.dart' as _i2;
import 'package:movies/domain/usecases/get_movies_recommendations.dart' as _i3;
import 'package:movies/domain/usecases/get_watchlist_status_movie.dart' as _i4;
import 'package:movies/domain/usecases/remove_watchlist.dart' as _i6;
import 'package:movies/domain/usecases/save_watchlist_movie.dart' as _i5;
import 'package:movies/presentation/bloc/movies_detail_bloc.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetMovieDetail_0 extends _i1.SmartFake
    implements _i2.GetMovieDetail {
  _FakeGetMovieDetail_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetMovieRecommendations_1 extends _i1.SmartFake
    implements _i3.GetMovieRecommendations {
  _FakeGetMovieRecommendations_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchListStatusMovie_2 extends _i1.SmartFake
    implements _i4.GetWatchListStatusMovie {
  _FakeGetWatchListStatusMovie_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSaveWatchlistMovie_3 extends _i1.SmartFake
    implements _i5.SaveWatchlistMovie {
  _FakeSaveWatchlistMovie_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveWatchlistMovie_4 extends _i1.SmartFake
    implements _i6.RemoveWatchlistMovie {
  _FakeRemoveWatchlistMovie_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieDetailState_5 extends _i1.SmartFake
    implements _i7.MovieDetailState {
  _FakeMovieDetailState_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieDetailBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDetailBloc extends _i1.Mock implements _i7.MovieDetailBloc {
  MockMovieDetailBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetMovieDetail get getMovieDetail =>
      (super.noSuchMethod(
            Invocation.getter(#getMovieDetail),
            returnValue: _FakeGetMovieDetail_0(
              this,
              Invocation.getter(#getMovieDetail),
            ),
          )
          as _i2.GetMovieDetail);

  @override
  _i3.GetMovieRecommendations get getMovieRecommendations =>
      (super.noSuchMethod(
            Invocation.getter(#getMovieRecommendations),
            returnValue: _FakeGetMovieRecommendations_1(
              this,
              Invocation.getter(#getMovieRecommendations),
            ),
          )
          as _i3.GetMovieRecommendations);

  @override
  _i4.GetWatchListStatusMovie get getWatchListStatusMovie =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchListStatusMovie),
            returnValue: _FakeGetWatchListStatusMovie_2(
              this,
              Invocation.getter(#getWatchListStatusMovie),
            ),
          )
          as _i4.GetWatchListStatusMovie);

  @override
  _i5.SaveWatchlistMovie get saveWatchlistMovie =>
      (super.noSuchMethod(
            Invocation.getter(#saveWatchlistMovie),
            returnValue: _FakeSaveWatchlistMovie_3(
              this,
              Invocation.getter(#saveWatchlistMovie),
            ),
          )
          as _i5.SaveWatchlistMovie);

  @override
  _i6.RemoveWatchlistMovie get removeWatchlistMovie =>
      (super.noSuchMethod(
            Invocation.getter(#removeWatchlistMovie),
            returnValue: _FakeRemoveWatchlistMovie_4(
              this,
              Invocation.getter(#removeWatchlistMovie),
            ),
          )
          as _i6.RemoveWatchlistMovie);

  @override
  _i7.MovieDetailState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeMovieDetailState_5(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i7.MovieDetailState);

  @override
  _i8.Stream<_i7.MovieDetailState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i8.Stream<_i7.MovieDetailState>.empty(),
          )
          as _i8.Stream<_i7.MovieDetailState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i7.MovieDetailEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i7.MovieDetailEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i7.MovieDetailState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i7.MovieDetailEvent>(
    _i9.EventHandler<E, _i7.MovieDetailState>? handler, {
    _i9.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i9.Transition<_i7.MovieDetailEvent, _i7.MovieDetailState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void onChange(_i9.Change<_i7.MovieDetailState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
