// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC66I3jD5LV-YHR7kCs_JYU1Snr3ne-QkA',
    appId: '1:1029656951587:web:08aca69f6ac1677ce36a96',
    messagingSenderId: '1029656951587',
    projectId: 'ditonton-3908b',
    authDomain: 'ditonton-3908b.firebaseapp.com',
    storageBucket: 'ditonton-3908b.firebasestorage.app',
    measurementId: 'G-SW1X49MSJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp6_tIeWLiX7P4SbeTovz-KYuMMqI9ebo',
    appId: '1:1029656951587:android:bebe906dfb0a035fe36a96',
    messagingSenderId: '1029656951587',
    projectId: 'ditonton-3908b',
    storageBucket: 'ditonton-3908b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbka-H2WjqneoRLsKX42mEF1BrgJBNebY',
    appId: '1:1029656951587:ios:1ab13550daf1df01e36a96',
    messagingSenderId: '1029656951587',
    projectId: 'ditonton-3908b',
    storageBucket: 'ditonton-3908b.firebasestorage.app',
    iosBundleId: 'com.example.flutterTvSeriesApp',
  );
}
